version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:${DB_PORT}'
  redis:
    image: redis:7.0.5-alpine
    restart: always
    container_name: redis
    ports:
      - 6379:6379