services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: pg_test
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}