services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: pg_dev
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env.development
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"